# to install this environment:
# conda env create -f environment.yml
name: open-gira
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:  # delegate to pip for non-conda packages
    - nismod-snail==0.2.1 # vector-raster intersections
    - osmium==3.2.0       # OpenStreetMap protobuf handling
    - snkit               # spatial network cleaning
    - --editable .        # open_gira helper package
  - black               # formatter
  - cython==0.29.28     # c--python interface
  - contextily          # basemaps for plots
  - datashader          # plotting large datasets
  - flake8              # linter
  - gdal>=3.3           # command-line tools for spatial data
  - geopandas>=0.11.0   # geospatial dataframes
  - geopy               # geocoding client
  - ipykernel           # notebook support
  - jupyter             # notebook support
  - matplotlib==3.7.1   # basic plotting
  - nb_conda_kernels    # notebook support
  - netCDF4             # NetCDF file format
  - networkx            # networks
  - numpy~=1.22.0       # data arrays
  - openpyxl            # Excel file format
  - pathos              # multiprocessing
  - pyarrow             # parquet file format, Arrow data exchange
  - aws-sdk-cpp=1.8.186
  # workaround for a bug in aws-sdk-cpp, which is used by pyarrow
  # https://issues.apache.org/jira/browse/ARROW-15141
  # https://github.com/apache/arrow/pull/14157
  - pyogrio             # vectorised geospatial file i/o
  - pyproj>=3.3.1       # geographic projections
  - pyrosm              # python OpenStreetMap network reader
  - pytest              # testing
  - pytest-xdist        # parallelise testing across CPUs
  - rasterio            # raster file formats
  - rasterstats         # raster statistics
  - requests            # make HTTP requests
  - rioxarray           # xarray datasets from raster files
  - scipy               # scientific computing library
  - spatialpandas       # plotting large datasets
  - snakemake==7.18.2   # workflow management
  - tabulate==0.8.10    # snakemake dependency with bug in 9.0.0, pin previous
  # https://github.com/snakemake/snakemake/issues/1891
  - tqdm==4.62.3        # progress bars
  - zenodo_get          # data download client
