# Input data and output locations
output_dir: 'results'

# This should be a named list of files that specify hazard raster files
# to retrieve using wget -i
hazard_datasets:
#  aqueduct-coast: 'https://raw.githubusercontent.com/mjaquiery/aqueduct/main/tiffs.txt'
  aqueduct-river: 'https://raw.githubusercontent.com/mjaquiery/aqueduct/main/rivers.txt'

# OSM dataset
infrastructure_datasets:
  tanzania-latest: 'https://download.geofabrik.de/africa/tanzania-latest.osm.pbf'
#  wales-latest: 'https://download.geofabrik.de/europe/great-britain/wales-latest.osm.pbf'
#  tanzania-mini: 'https://raw.githubusercontent.com/mjaquiery/aqueduct/main/tanzania-mini.osm.pbf'

# Number of slices to cut dataset into -- must be a square number
slice_count: 1
# Osmium tags to retain in the geoparquet files
keep_tags: 'highway'
# Filters definition
osmium_tags_filters_file: "config/highway-core.txt"

# Options for exposure tif file generation
exposure_tifs:
  # When generating exposure summaries, filter by cells with at >= exposure_threshold m of flooding
  exposure_threshold: 0.5
  # Used when scaling raster files, values < 1 will downsample
  scaling_factor: 0.1
  # Used to determine how resampling occurs. Valid values are in rasterio.enums.Resampling.
  resampling_mode: 'bilinear'
  plot:
    raster:
      cmap: 'Reds'