# Input data and output locations
output_dir: 'results'

## Aqueduct Analysis ##
# This should be a named list of files that specify hazard raster files
# to retrieve using wget -i
hazard_datasets:
  aqueduct-coast: 'https://raw.githubusercontent.com/mjaquiery/aqueduct/main/tiffs.txt'
  aqueduct-river: 'https://raw.githubusercontent.com/mjaquiery/aqueduct/main/rivers.txt'

# OSM dataset #
infrastructure_datasets:
  africa-latest: 'http://download.geofabrik.de/africa-latest.osm.pbf'
  egypt-latest: 'http://download.geofabrik.de/africa/egypt-latest.osm.pbf'
  kenya-latest: 'http://download.geofabrik.de/africa/kenya-latest.osm.pbf'
  tanzania-latest: 'https://download.geofabrik.de/africa/tanzania-latest.osm.pbf'
  tanzania-mini: 'https://raw.githubusercontent.com/mjaquiery/aqueduct/main/tanzania-mini.osm.pbf'
  wales-latest: 'https://download.geofabrik.de/europe/great-britain/wales-latest.osm.pbf'

# Number of slices to cut dataset into -- must be a square number
slice_count: 9

# road, rail, etc.
transport_type: 'road'

# Osmium tags to retain in the geoparquet files
# these must be specified as a single string, with each tag comma seperated e.g. 'highway, surface'
keep_tags: 'highway, surface, bridge, maxspeed, lanes'
# Filters definition: only keep objects with highway tags from the following set
osmium_tags_filters_file: "config/highway-secondary.txt"
# CRS OSM uses
osm_epsg: 4326

# road network specific configuration
# location of input data for annotating road networks
road_default_shoulder_width_metres: 1.5
road_default_lane_width_metres: 6.5
road_flow_cost_time_factor: 0.49
# if the following data can be sourced/hosted online, remove these config entries and download instead
road_speeds_path: 'local_data/global_road_speeds.xlsx'
road_rehabilitation_costs_path: 'local_data/rehabilitation_costs.xlsx'
transport_costs_path: 'local_data/transport_costs.csv'

# When generating exposure summaries, filter by cells with at >= exposure_threshold m of flooding
exposure_threshold: 0.5

## STORM Power Network Analysis ##
# width and height of dataset-splitting box (must be factor of 180)
box_width_height: 5

# List of boxes to analyse (only). Note that this must be known for the box_width_height value entered above. Put None to evaluate globally
specific_boxes: [1102, 1103, 1104]

# REGIONS #
# Regions in which to analyse. List of strings. Options: "EP", "NA", "NI", "SI", "SP", "WP". Include all for global analysis. If specific boxes are selected, this must be coherent with REGIONS
regions: ["NA"]

# SAMPLES #
# Synthetic data sample upper value (inclusive).Value from 0 to 9 to analyse for all years and regions.
sample_upper: 0

# Individual samples to investigate. Will override sample_upper. Write None to use sample_upper. List of floats or strings
samples_indiv: None

# Further Configuration #
# Storms will be analysed in batches of this value. Higher value: quicker process. Lower value: better memory. It is recommended to tweak this value dependent on the machine's available memory and/or user requirements (500 is often a good starting value). Note that at below 25, attempts are made to record which files store which data as to only load the relevant wind csv files. This may explain increases/decreases in performance.
storm_batches: 30

# If set to True then wind_extracter will overwrite existing wind files. It is recommended to keep this as False unless changes are made in the wind configuration files/scripts.
wind_rerun: False
