name: pyTest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yml
        environment-name: open-gira
        cache-env: true

    - name: Cache osmium-tool
      id: cache-osmium-tool
      uses: actions/cache@v2
      with:
        path: osmium-tool/build
        key: osmium-v1.14.0-libosmium-v2.18.0-cache_bust-v2

    - name: Build osmium-tool
      if: steps.cache-osmium-tool.outputs.cache-hit != 'true'
      run: |
        sudo apt install build-essential cmake libboost-program-options-dev \
                    libexpat1-dev zlib1g-dev libbz2-dev gdal-bin
        git clone https://github.com/mapbox/protozero
        git clone --branch v2.18.0 --depth 1 https://github.com/osmcode/libosmium
        git clone --branch v1.14.0 --depth 1 https://github.com/osmcode/osmium-tool
        cd osmium-tool
        mkdir build
        cd build
        cmake ..
        make
        cd ../..

    - name: Test with pytest
      # use a 'login shell', thereforce sourcing .bashrc, necessary for umamba
      shell: bash -l {0}
      # uses pytest-xdist to parallelise (2 CPUs on standard GH Actions runner)
      run: |
        export PATH="$PATH:$(pwd)/osmium-tool/build"
        osmium --version
        python -m pytest -n auto tests/
