name: Run tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get osmium-tool dependencies
      run: |
        sudo apt install build-essential cmake libboost-program-options-dev \
                    libexpat1-dev zlib1g-dev libbz2-dev
        git clone https://github.com/mapbox/protozero
        git clone --branch v2.17.1 --depth 1 https://github.com/osmcode/libosmium
        git clone --branch v1.13.2 --depth 1 https://github.com/osmcode/osmium-tool

    - name: Cache osmium-tool
      id: cache-osmium-tool
      uses: actions/cache@v2
      with:
        path: ./osmium-tool/build
        key: osmium-v1.13.2-libosmium-v2.17.1

    - name: Build osmium-tool
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: |
        cd osmium-tool
        mkdir build
        cd build
        cmake ..
        make
        cd ../..

    - name: Add osmium-tool to PATH
      run: |
        export PATH="$PATH:./osmium-tool/build"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pip install pytest
        python -m pytest .tests
